name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lab11/requirements.txt  # Путь к файлу requirements.txt в папке lab11

      - name: Run tests
        run: |
          pytest lab11/labs11test.py --junitxml=lab11/report.xml  # Запуск тестов с отчетом в папке lab11
        continue-on-error: true

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: lab11/report.xml  # Путь к отчету в папке lab11
