name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r 11Lab/requirements.txt

      - name: Run tests
        run: |
          pytest 11Lab/main_test.py --junitxml=11Lab/report.xml
        continue-on-error: true

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: 11Lab/report.xml
